# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IntelliSignals
email: contact@intellisignals.com
description: > # this means to ignore newlines until "baseurl:"
        Intelligent systems over Cloud
baseurl: "/intelli"
twitter_username: 
github_username: 

# Build settings
markdown: kramdown

#Exclude Tags , comma separated
main_ignore_posts_with_tags: 'troubleshooting'
tagline: 'BigData, Analytics and Cloud'

theme: jekyll-theme-slate
